// This file has been generated by Specta. Do not edit this file manually.
export type ExerciseDetails = {
	category: string,
	id: number,
	name: string,
	reps: number,
	weight: number | null,
	rm: number | null,
	workouts: string[],
	series: { [key in string]: WorkoutSerie[] },
	pr_date: string,
};

export type ExerciseListItem = {
	category: string,
	id: number,
	name: string,
	reps: number,
	weight: number | null,
	rm: number | null,
};

export type WorkoutDetails = {
	name: string,
	date: string,
	timestamp: string,
	total_elapsed_time: string,
	active_time: string,
	total_calories: number,
	metabolic_calories: number,
	avg_heart_rate: number,
	max_heart_rate: number,
	exercises: string[],
	series: { [key in string]: WorkoutSerie[] },
};

export type WorkoutListItem = {
	name: string,
	date: string,
	timestamp: string,
};

export type WorkoutSerie = {
	idx: number,
	reps: number,
	weight: number | null,
};

export type WorkoutSeriesUpdate = {
	timestamp: string,
	series: WorkoutSerie[],
};
