-- Aux tables for session

ALTER TABLE ADDITIONAL_DATA DROP COLUMN laps;

CREATE TABLE LAP (
    session INTEGER NOT NULL,
    idx INTEGER NOT NULL,
    start_latitude INTEGER,
    start_longitude INTEGER,

    PRIMARY KEY (session, idx),
    FOREIGN KEY (session) REFERENCES SESSION(date) ON DELETE CASCADE
);
CREATE INDEX LAP_SESSION ON LAP(session);

ALTER TABLE SERIE RENAME TO "SET";

DROP INDEX SERIE_EXERCISE;
CREATE INDEX SET_EXERCISE ON "SET"(exercise_category, exercise_id);

DROP INDEX SERIE_SESSION;
CREATE INDEX SET_SESSION ON "SET"(session);

DROP INDEX SERIE_PR;
CREATE INDEX SET_PR ON "SET"(pr);

DROP INDEX SERIE_EXERCISE_PR;
CREATE UNIQUE INDEX SET_EXERCISE_PR ON "SET"(exercise_category, exercise_id) WHERE pr = 1;

DROP INDEX BODY_METRIC_DATE;

ALTER TABLE ADDITIONAL_DATA DROP COLUMN cadences;
ALTER TABLE ADDITIONAL_DATA DROP COLUMN powers;
ALTER TABLE ADDITIONAL_DATA DROP COLUMN respirations;