-- Drop indexes that duplicate the leading column of their primary key

DROP INDEX IF EXISTS SET_SESSION;
DROP INDEX IF EXISTS LAP_SESSION;
DROP INDEX IF EXISTS SUB_SPORT_SPORT;
DROP INDEX IF EXISTS EXERCISE_EXERCISE_CATEGORY;
