-- Add aditional indexes and device column for session

DROP INDEX IF EXISTS HEART_RATE_ID;
DROP INDEX IF EXISTS HEART_RATE_SESSION;
CREATE INDEX IF NOT EXISTS HEART_RATE_SESSION ON HEART_RATE(session);

ALTER TABLE session ADD COLUMN device TEXT DEFAULT NULL REFERENCES DEVICE(serial) ON DELETE CASCADE;