--- Database reingeniering

ALTER TABLE HEART_RATE RENAME TO OLD_HEART_RATE;

CREATE TABLE IF NOT EXISTS HEART_RATE(
    session INTEGER NOT NULL,
    records BLOB NOT NULL,

    PRIMARY KEY(session),

    FOREIGN KEY(session) REFERENCES SESSION(date) ON DELETE CASCADE
);

INSERT INTO HEART_RATE (session, records)
SELECT
    session,
    unhex(GROUP_CONCAT(printf('%02x', hr), '' ORDER BY idx))
FROM OLD_HEART_RATE
GROUP BY session;

DROP TABLE OLD_HEART_RATE;

ALTER TABLE USER RENAME TO BODY_METRICS;

ALTER TABLE SESSION ADD COLUMN VOLUME REAL NOT NULL DEFAULT 0;
UPDATE SESSION as ses set volume=(
	SELECT 
		COALESCE(SUM(ser.weight*ser.reps), 0)
	FROM 
		SERIE as ser
	WHERE
		ser.session=ses.date
) 