--- Speed

ALTER TABLE GPS_COORDINATES RENAME TO COORDINATES;

CREATE TABLE IF NOT EXISTS SPEEDS(
    session INTEGER NOT NULL,
    records BLOB NOT NULL,

    PRIMARY KEY(session),

    FOREIGN KEY(session) REFERENCES SESSION(date) ON DELETE CASCADE
);
