name: AUR release

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    if: startsWith(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Extract version
        id: version
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' src-tauri/Cargo.toml | head -n1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Get last git tag
        id: git_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
          TAG=${TAG#v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Check version vs tag
        id: check_version
        run: |
          if [ "${{ steps.version.outputs.version }}" != "${{ steps.git_tag.outputs.tag }}" ]; then
            echo "different=true" >> $GITHUB_OUTPUT
          else
            echo "different=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate release artifacts
        if: steps.check_version.outputs.different == 'true'
        run: |
          make release

      - name: Setup SSH for AUR
        env:
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        if: steps.check_version.outputs.different == 'true'
        run: |
          mkdir -p ~/.ssh

          echo "$AUR_SSH_PRIVATE_KEY" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur

          cat >> ~/.ssh/config <<EOF
          Host aur.archlinux.org
            IdentityFile ~/.ssh/aur
            User aur
            StrictHostKeyChecking no
          EOF

      - name: Publish package to AUR
        env:
          VERSION: ${{ steps.version.outputs.version }}
        if: steps.check_version.outputs.different == 'true'
        run: |
          git clone ssh://aur@aur.archlinux.org/garmin-tracker-rs.git garmin_tracker_rs_repo

          cd garmin_tracker_rs_repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          cp ../dist/PKGBUILD .
          cp ../dist/.SRCINFO .

          git add PKGBUILD .SRCINFO 

          if ! git diff --cached --quiet; then
            git commit -m "Release ${VERSION}-1"
            git push
          else
            echo "No changes to publish"
          fi

      - name: Create Git tag
        if: steps.check_version.outputs.different == 'true'
        run: |
          VERSION=${{ steps.version.outputs.version }}
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Create GitHub release
        if: steps.check_version.outputs.different == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body_path: dist/changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
